# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install and Build 🔧
        uses: actions/setup-node@v1
      - run: npm install
          
      - name: Deploy 🚀
      - uses: actions/setup-node@v1
      - uses: actions/checkout@v2
        run: |
          git config user.name "Vineethbc"
          git config user.email "vineethbc@gmail.com"
          npm run deploy
      # with:
      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      #     npm run build
      #   env:
      #       CI: true
      # - name: Deploy 🚀
      #   uses: JamesIves/github-pages-deploy-action@3.6.2
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     BRANCH: gh-pages # The branch the action should deploy to.
      #     FOLDER: .next # The folder the action should deploy.
      #     CLEAN: true # Automatically remove deleted files from the deploy branch
